# Generated by Django 3.0.2 on 2020-10-17 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('hero', models.CharField(max_length=50)),
                ('heroine', models.CharField(max_length=50)),
                ('director', models.CharField(max_length=50)),
                ('producer', models.CharField(max_length=50)),
                ('music', models.CharField(max_length=50)),
                ('release', models.CharField(max_length=50)),
            ],
        ),
    ]
